week_now: 23
sources:
  direct:
  - DIRECTO
  - Caroline Walker
  - Online Request
  - Over Phone
  - Other
  outfitters:
  - RONSOR
  - PRG
  - URIBE
  - TUQUI
  - Fishing Patagonia
  - Patagonia Outfitters (JT)
  - FLY WATER
  - Logreco
  - TECHERA
  - JUSTINO
  - Burell
  - Justi
  - Junior
  - CORDERO
  - Obejero
  - Segovia
  - Pancho Panzer
  - Alex T
  - Andres Muller
  - El encuentro flyfishing
  agencies:
  - Lucas Rodriguez
  - Clement Cloz
  - Attipica
  - Travel Agency (ARG)
  - Simon C&R
  - Signature DMC
tgn:
  start_date: '2026-11-01'
  end_date: '2027-04-30'
foyel_tgn:
  start_date: '2027-03-01'
  end_date: '2027-04-30'
lodges:
  rhl:
    name: River House Lodge
    sub: Río Chimehuin · San Martín de los Andes
    logo: null
    ref:
      refBN: 1078
      refRev: 660467
      p:
        Nov: 127
        Dic: 227
        Ene: 251
        Feb: 218
        Mar: 172
        Abr: 83
      channels:
        direct: 104
        outfitters:
        - name: PRG
          bn: 389
        - name: RONSOR
          bn: 206
        - name: URIBE
          bn: 87
        - name: Patagonia Outfitters (JT)
          bn: 72
        - name: JUSTINO
          bn: 18
        - name: TUQUI
          bn: 10
        - name: Obejero
          bn: 10
        - name: Junior
          bn: 9
        - name: CORDERO
          bn: 8
        - name: Fishing Patagonia
          bn: 6
        agencies:
        - name: Lucas Rodriguez
          bn: 72
        - name: Clement Cloz
          bn: 35
        - name: Travel Agency (ARG)
          bn: 18
        - name: Attipica
          bn: 15
  ap:
    name: Arroyo Pescado
    sub: Esquel · Chubut
    logo: null
    ref:
      refBN: 229
      refRev: 118009
      p:
        Nov: 12
        Dic: 79
        Ene: 62
        Feb: 16
        Mar: 30
        Abr: 30
      channels:
        direct: 28
        outfitters:
        - name: El encuentro flyfishing
          bn: 41
        - name: Logreco
          bn: 31
        - name: PRG
          bn: 30
        - name: Segovia
          bn: 23
        - name: Alex T
          bn: 3
        - name: Pancho Panzer
          bn: 2
        - name: Andres Muller
          bn: 2
        agencies:
        - name: Simon C&R
          bn: 8
  foyel:
    name: Foyel
    sub: Temporada otoño · marzo a abril
    logo: null
    ref:
      refBN: 81
      refRev: 0
      p:
        Mar: 0
        Abr: 0
